global using System.Data;
global using System.Data.Common;
global using MsParameter = Microsoft.Data.SqlClient.SqlParameter;
global using MsCommand = Microsoft.Data.SqlClient.SqlCommand;
global using MsConnection = Microsoft.Data.SqlClient.SqlConnection;
global using MsException = Microsoft.Data.SqlClient.SqlException;
global using MsError = Microsoft.Data.SqlClient.SqlError;
global using SysParameter = System.Data.SqlClient.SqlParameter;
global using SysCommand = System.Data.SqlClient.SqlCommand;
global using SysConnection = System.Data.SqlClient.SqlConnection;
global using SysException = System.Data.SqlClient.SqlException;
global using SysError = System.Data.SqlClient.SqlError;
global using Microsoft.Extensions.DiagnosticAdapter;
global using Microsoft.SqlServer.Management.Common;
global using VerifyTests.SqlServer;